//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace is_takip.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblMesajlar
    {
        public int ID { get; set; }
        public Nullable<int> Gonderen { get; set; }
        public Nullable<int> Alan { get; set; }
        public string Basliq { get; set; }
        public string mesaj { get; set; }
        public Nullable<System.DateTime> Tatix { get; set; }
        public Nullable<bool> Durum { get; set; }
    
        public virtual TblFirma TblFirma { get; set; }
        public virtual TblFirma TblFirma1 { get; set; }
        public virtual TblPersonel TblPersonel { get; set; }
    }
}
